name: Build and Test C# Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print Working Directory and List Files
      run: |
        pwd
        ls -R

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0'

    - name: Restore dependencies
      run: dotnet restore ./SportradarLibrary/SportradarLibrary.csproj

    - name: Build
      run: dotnet build ./SportRadarLibraryTestSuite/SportRadarLibraryTestSuite.csproj --configuration Debug

    - name: Debug Directory Contents
      run: ls -R ./SportRadarLibraryTestSuite/bin/Debug/net8.0/
      
    - name: Install Playwright Browsers
      run: pwsh ./SportRadarLibraryTestSuite/bin/Debug/net8.0/playwright.ps1 install

    - name: Run NUnit Tests
      run: dotnet test ./SportRadarLibraryTestSuite/SportRadarLibraryTestSuite.csproj --configuration Debug --no-build --logger "console;verbosity=detailed" --collect:"XPlat Code Coverage"

    - name: Upload Test Results
      uses: actions/upload-artifact@v3
      with:
        name: TestResults
        path: SportRadarLibraryTestSuite/TestResults/*.trx
