name: Build and Test C# Project

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print Working Directory and List Files
      run: |
        pwd
        ls -R

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0' # Specify the version of .NET you are using

    - name: Restore dependencies
      run: dotnet restore ./SportRadar/SportradarLibrary/SportradarLibrary.csproj

    - name: Build
      run: dotnet build ./SportRadar/SportradarLibrary/SportradarLibrary.csproj --configuration Release --no-restore

    - name: Run tests
      run: dotnet test ./SportRadar/SportRadarLibraryTestSuite/SportRadarLibraryTestSuite.csproj --configuration Release --no-build --verbosity normal
